name: Build & Publish

on:
  push:
    branches: [main]
    paths:
      - 'packages/**/PKGBUILD'

env:
  BUCKET: aur-repo
  ENDPOINT: https://pub-c388a4aca5ea4050a0afd58c60a78cb3.r2.dev
  AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_KEY }}

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: set-matrix
        run: |
          changed=$(git diff --name-only HEAD^..HEAD -- packages/*/PKGBUILD | xargs -r dirname | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$changed" >> $GITHUB_OUTPUT

  build:
    needs: list
    if: needs.list.outputs.matrix != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkgdir: ${{ fromJson(needs.list.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      # 1) 用官方 Arch 镜像编译 ==========================
      - name: Build package in Arch Docker
        run: |
          docker run --rm -v $PWD:/src -w /src \
            archlinux:latest bash -ec '
              pacman -Syu --noconfirm
              pacman -S --noconfirm base-devel sudo
              cd ${{ matrix.pkgdir }}
              makepkg --syncdeps --noconfirm --cleanbuild --skipinteg
            '
          echo "PKG=$(find ${{ matrix.pkgdir }} -name "*.pkg.tar.zst" -printf '%f\n')" >> $GITHUB_ENV

      # 2) 后续流程不变 ==================================
      - name: Install rclone
        run: sudo apt install -y rclone

      - name: Push to R2
        run: |
          rclone config create r2 s3 provider=Cloudflare \
                access_key_id=$AWS_ACCESS_KEY_ID \
                secret_access_key=$AWS_SECRET_ACCESS_KEY \
                endpoint=$ENDPOINT
          arch=$(tar -xfO "${{ matrix.pkgdir }}/${{ env.PKG }}" .PKGINFO | grep '^arch = ' | cut -d' ' -f3)
          [ "$arch" = "any" ] && target="any" || target="x86_64"
          mkdir -p repo/$target
          rclone copy r2:$BUCKET/$target/$BUCKET.db.tar.gz repo/$target/ || true
          rclone copy r2:$BUCKET/$target/$BUCKET.files.tar.gz repo/$target/ || true
          cp "${{ matrix.pkgdir }}/${{ env.PKG }}" repo/$target/
          repo-add -n -R repo/$target/$BUCKET.db.tar.gz repo/$target/*.pkg.tar.zst
          rclone copy repo/$target/ r2:$BUCKET/$target/ --progress